/**
 * ProjectSentinel Domain Data Types
 * Reference Standard: SIH 2026 Problem Statement SIH26103
 * Architectural Principle: Credible separation between Source Data, Calculations,
 * Prototype Model Outputs, Demo Scenarios, and External Feeds.
 */

export type DataOriginCategory = 
  | 'SOURCE_DERIVED'        // Extracted directly from official PAIMANA / MoSPI public records
  | 'CALCULATED_ANALYTIC'   // Reproducibly calculated from loaded project records
  | 'MODEL_PROTOTYPE'       // Generated by current prototype risk scoring logic
  | 'DEMO_SIMULATION'       // Curated representative scenario for testing
  | 'EXTERNAL_DISCONNECTED';// External feed stub (not connected in prototype)

export type RiskLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INSUFFICIENT_DATA';
export type RiskTrendDirection = 'INCREASING_FAST' | 'INCREASING' | 'STABLE' | 'DECREASING';
export type UrgencyLevel = 'IMMEDIATE_48H' | 'CYCLE_PRIORITY' | 'SCHEDULED_REVIEW';
export type DataQualityTier = 'SUFFICIENT' | 'PARTIAL' | 'INSUFFICIENT' | 'VALIDATION_REQUIRED';

export type InfrastructureSector = 
  | 'Highways & Roads'
  | 'Railways & Metros'
  | 'Power & Renewable'
  | 'Petroleum & Natural Gas'
  | 'Ports & Shipping'
  | 'Civil Aviation'
  | 'Urban Development & Water';

export interface ProjectEntity {
  id: string;
  code: string;
  name: string;
  sector: InfrastructureSector;
  ministry: string;
  implementingAgency: string;
  state: string;
  region: string;
  coordinates: [number, number]; // [lat, lng]
  sanctionedDate: string;
  originalCompletionDate: string;
  anticipatedCompletionDate: string;
  sanctionedCostCr: number;
  anticipatedCostCr: number;
  cumulativeExpenditureCr: number;
  physicalProgressPct: number;
  financialProgressPct: number;
  dataQuality: DataQualityTier;
  dataOrigin: DataOriginCategory;
  lastReportingPeriod: string;
}

export interface RiskFactor {
  id: string;
  category: 'LAND_ACQUISITION' | 'CONTRACTOR_CAPACITY' | 'STATUTORY_CLEARANCES' | 'GEOLOGICAL' | 'FINANCIAL_FLOW' | 'UTILITY_SHIFTING';
  title: string;
  weightPct: number;
  severity: 'CRITICAL' | 'HIGH' | 'MODERATE';
  groundObservation: string;
  paimanaFieldRef: string;
  isSimulatedScenario: boolean;
}

export type EvidenceType = 
  | 'MONTHLY_DPR'
  | 'SITE_INSPECTION'
  | 'STATUTORY_NOC'
  | 'FINANCIAL_AUDIT'
  | 'DRONE_AERIAL'
  | 'CONTRACTOR_NOTICE';

export type EvidenceProvenanceCategory =
  | 'SOURCE'
  | 'CALCULATED'
  | 'PROTOTYPE_MODEL'
  | 'SIMULATED'
  | 'NOT_CONNECTED';

export type EvidenceVerificationStatus = 
  | 'SOURCE_VERIFIED' 
  | 'DEMO_VALIDATED' 
  | 'SCHEMA_CHECKED' 
  | 'FLAGGED_INCONSISTENCY' 
  | 'PENDING_CONFIRMATION' 
  | 'UNCONNECTED'
  | 'VERIFIED';

export interface EvidenceRecord {
  id: string;
  projectId: string;
  projectName: string;
  projectCode: string;
  issueId?: string;
  riskSignalId?: string;
  milestoneId?: string;
  milestoneTitle?: string;
  title: string;
  evidenceType: EvidenceType;
  source: string;
  recordDate: string;
  description: string;
  observedContent: string;
  interpretation: string;
  provenance: EvidenceProvenanceCategory;
  provenanceLabel: string;
  integrityReference: string;
  verificationStatus: EvidenceVerificationStatus;
  isDemo: boolean;
  relatedActionIds: string[];
  // Backwards compatibility aliases
  type?: string;
  documentTitle?: string;
  date?: string;
  issuingAuthority?: string;
  summary?: string;
  isSimulatedRecord?: boolean;
}

export interface ActionGuidance {
  criticalPathMilestone: string;
  projectedStallDays: number;
  competentAuthority: string;
  fieldOfficers: string[];
  recommendedDecision: string;
  statutoryNextStep: string;
  escalationLevel: string;
}

export interface HistoricalMonitoringCycleRecord {
  cycleId: string;
  reportingPeriod: string;
  reportingDate: string;
  physicalProgressPct: number;
  physicalProgressDeltaPct: number;
  cumulativeExpenditureCr: number;
  expenditureDeltaCr: number;
  anticipatedCompletionDate: string;
  scheduleShiftMonths: number;
  anticipatedCostCr: number;
  costRevisionDeltaCr: number;
  cycleRemark: string;
}

export interface EvidenceProvenanceItem {
  id: string;
  documentTitle: string;
  provenanceSource: string;
  reportingPeriod: string;
  evidenceType: 'MONTHLY_DPR' | 'SITE_INSPECTION' | 'DRONE_AERIAL' | 'FINANCIAL_AUDIT' | 'STATUTORY_NOC' | 'CONTRACTOR_NOTICE';
  association: string;
  availabilityStatus: 'SOURCE_CONNECTED' | 'SAMPLE_RECORD' | 'NOT_CONNECTED';
  summary: string;
  isSimulatedDemo: boolean;
}

export interface AttentionQueueItem {
  project: ProjectEntity;
  riskScore: number; // 0.00 to 1.00 (Prototype output)
  riskLevel: RiskLevel;
  trend: RiskTrendDirection;
  trendDelta: number; // e.g. +0.14
  primarySignalCompact: string; // Compact 1-line phrase for cockpit decision surface
  primarySignalFull: string;    // Detailed text for inspector
  recentChangeCompact: string;  // Compact delta
  recentChangeFull: string;     // Detailed delta
  urgency: UrgencyLevel;
  recommendedActionText: string;
  modelConfidencePct: number;
  riskFactors: RiskFactor[];
  evidence: EvidenceRecord[];
  actionGuidance: ActionGuidance;
  scenarioTag: 'SIMULATED_SCENARIO' | 'HISTORICAL_BENCHMARK';
  historicalCycles: HistoricalMonitoringCycleRecord[];
  evidenceProvenance: EvidenceProvenanceItem[];
}

export interface PortfolioSummaryStats {
  // Calculated directly from loaded reference dataset in workspace
  loadedProjectsCount: number;
  loadedActiveCount: number;
  loadedDelayedCount: number;
  loadedDelayedRatioPct: number;
  loadedAtRiskCount: number; // Critical + High
  loadedSanctionedOutlayCr: number;
  loadedAnticipatedCostCr: number;
  loadedCostVarianceCr: number;
  loadedCostVariancePct: number;
  schemaCompatibleCount: number;
}

export interface RiskDistributionData {
  bySeverity: {
    critical: { count: number; pct: number };
    high: { count: number; pct: number };
    medium: { count: number; pct: number };
    low: { count: number; pct: number };
    insufficientData: { count: number; pct: number };
  };
  byTrend: {
    increasing: { count: number; pct: number };
    stable: { count: number; pct: number };
    decreasing: { count: number; pct: number };
  };
  sampleBasisText: string;
}

export interface QuarterlyTrendPoint {
  cycle: string;
  quarterLabel: string;
  portfolioAvgRiskIndex: number;
  criticalHighCount: number;
  delayedCount: number;
  resolvedCount: number;
  isIllustrative: boolean;
}

export interface DataQualitySummary {
  loadedTotal: number;
  sufficientCount: number;
  sufficientPct: number;
  partialCount: number;
  partialPct: number;
  insufficientCount: number;
  insufficientPct: number;
  validationRequiredCount: number;
  validationRequiredPct: number;
  schemaCheckStatus: string;
  productionIntegrationStatus: string;
  modelStatus: string;
  externalDataStatus: string;
}

/**
 * Early Warning Specific Types (Milestone 3)
 * Reference: SIH26103 Engineering Intelligence Standard
 */
export type EarlyWarningRiskState = 'HIGH_ATTENTION' | 'EMERGING_RISK' | 'WATCH' | 'STABLE';

export type CausalDriverCategory = 
  | 'STATUTORY_ENVIRONMENTAL'
  | 'LAND_ROW'
  | 'CONTRACTOR_EXECUTION'
  | 'FINANCIAL_EXPENDITURE'
  | 'UTILITY_INTERAGENCY'
  | 'GEOLOGICAL_TERRAIN'
  | 'OTHER_INSUFFICIENT';

export interface DriverClusterItem {
  id: string;
  category: CausalDriverCategory;
  categoryLabel: string;
  observedSignal: string;
  evidenceFieldMapping: string;
  interpretationStatus: string;
  affectedProjects: {
    projectId: string;
    projectCode: string;
    projectName: string;
    specificFinding: string;
  }[];
}

/**
 * Intervention & Escalation Types (Milestone 4)
 * Reference: SIH26103 Engineering Operations Standard
 */
export type InterventionStatus = 'NEW' | 'ACKNOWLEDGED' | 'UNDER REVIEW' | 'ESCALATED' | 'RESOLVED';

export type ResponsibleRole = 
  | 'Portfolio Officer'
  | 'Project Authority'
  | 'Project Manager'
  | 'Department/Nodal Officer'
  | 'Field Officer'
  | 'Auditor/Reviewer';

export interface ActionEvent {
  id: string;
  issueId: string;
  action: string;
  actorRole: ResponsibleRole | string;
  timestamp: string;
  note: string;
  previousState: InterventionStatus;
  newState: InterventionStatus;
}

export interface InterventionIssue {
  id: string;
  projectId: string;
  projectName: string;
  projectCode: string;
  sector: InfrastructureSector;
  state: string;
  sourceRiskSignalId: string;
  issueType: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  status: InterventionStatus;
  trend: RiskTrendDirection;
  trendDelta: number;
  primaryDriver: string;
  primaryDriverFieldRef: string;
  observedSignal: string;
  whyItMatters: string;
  responsibleRole: ResponsibleRole;
  assignedTo: string;
  reviewDue: string;
  createdAt: string;
  updatedAt: string;
  escalationLevel: string;
  officerNote: string;
  evidenceIds: string[];
  evidenceSummary: string;
  provenance: string;
  resolutionNote?: string;
  resolvedBy?: string;
  resolvedAt?: string;
  actionHistory: ActionEvent[];
}

export type LocationPrecision = 
  | 'CORRIDOR_EXTENT'
  | 'SITE_PERIMETER'
  | 'REGIONAL_LANDMARK'
  | 'ALIGNMENT_ROW'
  | 'INSUFFICIENT_DATA';

export interface WeatherExposureContext {
  isSimulated: boolean;
  precipitationProbabilityPct: number;
  rainfallIntensityMmHr: number;
  temperatureC: number;
  severeCondition: string;
  forecastPeriod: string;
  forecastTimestamp: string;
  feedStatus: 'NOT_CONNECTED_LIVE_FEED';
  provenanceLabel: string;
  feedLabel: string;
}

export interface ProjectActivityExposure {
  projectActivity: string;
  isActivitySimulated: boolean;
  milestoneId?: string;
  externalCondition: string;
  scheduleOverlap: string;
  projectSentinelContext: string;
  reviewStatus: string;
  deterministicOverlapLabel: string;
  modelContributionLabel: string;
  causationBoundaryNote: string;
}

export interface ExternalConditionsRecord {
  projectId: string;
  projectCode: string;
  projectName: string;
  sector: InfrastructureSector;
  stateRegion: string;
  projectLocation: string;
  locationPrecision: string;
  lastSourceUpdate: string;
  locationProvenance: 'SOURCE' | 'SIMULATED';
  weather: WeatherExposureContext;
  activityExposure: ProjectActivityExposure;
  relatedIssueId?: string;
  relatedEvidenceId?: string;
}
