/**
 * ProjectSentinel Domain Data Types
 * Reference Standard: SIH 2026 Problem Statement SIH26103
 * Architectural Principle: Credible separation between Source Data, Calculations,
 * Prototype Model Outputs, Demo Scenarios, and External Feeds.
 */

export type DataOriginCategory = 
  | 'SOURCE_DERIVED'        // Extracted directly from official PAIMANA / MoSPI public records
  | 'CALCULATED_ANALYTIC'   // Reproducibly calculated from loaded project records
  | 'MODEL_PROTOTYPE'       // Generated by current prototype risk scoring logic
  | 'DEMO_SIMULATION'       // Curated representative scenario for testing
  | 'EXTERNAL_DISCONNECTED';// External feed stub (not connected in prototype)

export type RiskLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INSUFFICIENT_DATA';
export type RiskTrendDirection = 'INCREASING_FAST' | 'INCREASING' | 'STABLE' | 'DECREASING';
export type UrgencyLevel = 'IMMEDIATE_48H' | 'CYCLE_PRIORITY' | 'SCHEDULED_REVIEW';
export type DataQualityTier = 'SUFFICIENT' | 'PARTIAL' | 'INSUFFICIENT' | 'VALIDATION_REQUIRED';

export type InfrastructureSector = 
  | 'Highways & Roads'
  | 'Railways & Metros'
  | 'Power & Renewable'
  | 'Petroleum & Natural Gas'
  | 'Ports & Shipping'
  | 'Civil Aviation'
  | 'Urban Development & Water';

export interface ProjectEntity {
  id: string;
  code: string;
  name: string;
  sector: InfrastructureSector;
  ministry: string;
  implementingAgency: string;
  state: string;
  region: string;
  coordinates: [number, number]; // [lat, lng]
  sanctionedDate: string;
  originalCompletionDate: string;
  anticipatedCompletionDate: string;
  sanctionedCostCr: number;
  anticipatedCostCr: number;
  cumulativeExpenditureCr: number;
  physicalProgressPct: number;
  financialProgressPct: number;
  dataQuality: DataQualityTier;
  dataOrigin: DataOriginCategory;
  lastReportingPeriod: string;
}

export interface RiskFactor {
  id: string;
  category: 'LAND_ACQUISITION' | 'CONTRACTOR_CAPACITY' | 'STATUTORY_CLEARANCES' | 'GEOLOGICAL' | 'FINANCIAL_FLOW' | 'UTILITY_SHIFTING';
  title: string;
  weightPct: number;
  severity: 'CRITICAL' | 'HIGH' | 'MODERATE';
  groundObservation: string;
  paimanaFieldRef: string;
  isSimulatedScenario: boolean;
}

export interface EvidenceRecord {
  id: string;
  type: 'DPR_SUBMISSION' | 'DRONE_SURVEY' | 'STATE_NOC' | 'EXPENSE_AUDIT' | 'CONTRACTOR_NOTICE' | 'INSPECTION_NOTE';
  documentTitle: string;
  date: string;
  issuingAuthority: string;
  summary: string;
  verificationStatus: 'VERIFIED' | 'FLAGGED_INCONSISTENCY' | 'PENDING_CONFIRMATION';
  isSimulatedRecord: boolean;
}

export interface ActionGuidance {
  criticalPathMilestone: string;
  projectedStallDays: number;
  competentAuthority: string;
  fieldOfficers: string[];
  recommendedDecision: string;
  statutoryNextStep: string;
  escalationLevel: string;
}

export interface AttentionQueueItem {
  project: ProjectEntity;
  riskScore: number; // 0.00 to 1.00 (Prototype output)
  riskLevel: RiskLevel;
  trend: RiskTrendDirection;
  trendDelta: number; // e.g. +0.14
  primarySignalCompact: string; // Compact 1-line phrase for cockpit decision surface
  primarySignalFull: string;    // Detailed text for inspector
  recentChangeCompact: string;  // Compact delta
  recentChangeFull: string;     // Detailed delta
  urgency: UrgencyLevel;
  recommendedActionText: string;
  modelConfidencePct: number;
  riskFactors: RiskFactor[];
  evidence: EvidenceRecord[];
  actionGuidance: ActionGuidance;
  scenarioTag: 'SIMULATED_SCENARIO' | 'HISTORICAL_BENCHMARK';
}

export interface PortfolioSummaryStats {
  // Calculated directly from loaded reference dataset in workspace
  loadedProjectsCount: number;
  loadedActiveCount: number;
  loadedDelayedCount: number;
  loadedDelayedRatioPct: number;
  loadedAtRiskCount: number; // Critical + High
  loadedSanctionedOutlayCr: number;
  loadedAnticipatedCostCr: number;
  loadedCostVarianceCr: number;
  loadedCostVariancePct: number;
  schemaCompatibleCount: number;
}

export interface RiskDistributionData {
  bySeverity: {
    critical: { count: number; pct: number };
    high: { count: number; pct: number };
    medium: { count: number; pct: number };
    low: { count: number; pct: number };
    insufficientData: { count: number; pct: number };
  };
  byTrend: {
    increasing: { count: number; pct: number };
    stable: { count: number; pct: number };
    decreasing: { count: number; pct: number };
  };
  sampleBasisText: string;
}

export interface QuarterlyTrendPoint {
  cycle: string;
  quarterLabel: string;
  portfolioAvgRiskIndex: number;
  criticalHighCount: number;
  delayedCount: number;
  resolvedCount: number;
  isIllustrative: boolean;
}

export interface DataQualitySummary {
  loadedTotal: number;
  sufficientCount: number;
  sufficientPct: number;
  partialCount: number;
  partialPct: number;
  insufficientCount: number;
  insufficientPct: number;
  validationRequiredCount: number;
  validationRequiredPct: number;
  schemaCheckStatus: string;
  productionIntegrationStatus: string;
  modelStatus: string;
  externalDataStatus: string;
}
