import React from 'react';
import { X, Database, ShieldAlert, CheckCircle2, GitBranch, Cpu, ArrowRight } from 'lucide-react';

interface DataArchitectureModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DataArchitectureModal: React.FC<DataArchitectureModalProps> = ({
  isOpen,
  onClose,
}) => {
  if (!isOpen) return null;

  return (
    <div className="action-drawer-overlay" onClick={onClose} role="dialog" aria-modal="true" style={{ justifyContent: 'center', alignItems: 'center' }}>
      <div 
        className="operational-panel" 
        onClick={(e) => e.stopPropagation()}
        style={{ width: '700px', maxWidth: '92vw', maxHeight: '85vh', overflowY: 'auto', margin: 'auto', boxShadow: '0 8px 32px rgba(0,0,0,0.2)' }}
      >
        <div className="panel-header" style={{ padding: '14px 20px' }}>
          <div className="panel-title-group">
            <div className="panel-title">
              <Database size={16} style={{ color: 'var(--admin-blue-800)' }} />
              <span>DATA ARCHITECTURE &amp; SOURCE BOUNDARY SPECIFICATION</span>
            </div>
            <div className="panel-subtitle">
              Strict separation between Source Data, Model Outputs, External Conditions, and Demo Layer
            </div>
          </div>
          <button onClick={onClose} className="drawer-close-btn">
            <X size={16} />
          </button>
        </div>

        <div className="panel-body" style={{ padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Notice banner */}
          <div style={{ padding: '10px 14px', backgroundColor: '#eff6ff', border: '1px solid #bfdbfe', borderRadius: '2px', fontSize: '12px', color: '#1e3a8a' }}>
            <strong>SIH 2026 Problem Statement SIH26103 Compliance Note:</strong><br />
            ProjectSentinel operates as an intelligence layer around PAIMANA (MoSPI) data. The application maintains strict isolation across data classifications so synthetic/demo values are never silently disguised as live telemetry.
          </div>

          {/* 4 Classification Layers */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            {/* Layer 1 */}
            <div style={{ padding: '12px', border: '1px solid var(--border-hairline)', borderRadius: '2px', backgroundColor: '#fafbfc' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color: 'var(--admin-blue-800)' }}>
                <GitBranch size={13} />
                <span>1. Real / Source-Derived Data</span>
              </div>
              <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '6px', lineHeight: 1.4 }}>
                Direct mappings from PAIMANA monthly progress reports: Project ID, Sanctioned Outlay, Sanctioned Date, Ministry/Agency, and Initial COD baseline.
              </div>
              <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '8px', fontFamily: 'var(--font-mono)' }}>
                Status: Schema Ready for MoSPI API
              </div>
            </div>

            {/* Layer 2 */}
            <div style={{ padding: '12px', border: '1px solid var(--border-hairline)', borderRadius: '2px', backgroundColor: '#fafbfc' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color: '#9a3412' }}>
                <Cpu size={13} />
                <span>2. Predictive Model Outputs</span>
              </div>
              <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '6px', lineHeight: 1.4 }}>
                Derived risk scores (0-1.00), urgency classifications, factor weight attributions, and delay probabilities generated by Sentinel Risk ML models.
              </div>
              <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '8px', fontFamily: 'var(--font-mono)' }}>
                Status: Calibrated on 10-Yr MoSPI Outturns
              </div>
            </div>

            {/* Layer 3 */}
            <div style={{ padding: '12px', border: '1px solid var(--border-hairline)', borderRadius: '2px', backgroundColor: '#fafbfc' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color: '#166534' }}>
                <CheckCircle2 size={13} />
                <span>3. External Conditions</span>
              </div>
              <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '6px', lineHeight: 1.4 }}>
                Satellite drone corridor verification, State Land Revenue records, DGRE avalanche alerts, and court registry environmental litigation status.
              </div>
              <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '8px', fontFamily: 'var(--font-mono)' }}>
                Status: Mock Verification Connectors
              </div>
            </div>

            {/* Layer 4 */}
            <div style={{ padding: '12px', border: '1px solid #fed7aa', borderRadius: '2px', backgroundColor: '#fff7ed' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', color: '#9a3412' }}>
                <ShieldAlert size={13} />
                <span>4. Demo / Reference Layer</span>
              </div>
              <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '6px', lineHeight: 1.4 }}>
                Currently active dataset containing 10 representative multi-sector central projects with authentic cost, schedule, and ground impediment records.
              </div>
              <div style={{ fontSize: '10px', color: '#9a3412', marginTop: '8px', fontFamily: 'var(--font-mono)', fontWeight: 600 }}>
                Active in National Cockpit View
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '8px' }}>
            <button onClick={onClose} className="btn-operational btn-primary-action" style={{ padding: '6px 14px' }}>
              Acknowledge &amp; Return to Cockpit
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
